/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'car-models': CarModel;
    promotions: Promotion;
    news: News;
    branches: Branch;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'car-models': CarModelsSelect<false> | CarModelsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * แก้ราคาและสเปกรถทุกรุ่นที่นี่ — แก้แล้วเว็บอัปเดตทันที
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-models".
 */
export interface CarModel {
  id: number;
  /**
   * เช่น Sealion 7
   */
  name: string;
  /**
   * ตัวพิมพ์เล็กและขีดกลาง เช่น sealion-7 — เปลี่ยนแล้วลิงก์เดิมจะเสีย
   */
  slug: string;
  /**
   * ใช้สำหรับปุ่มกรองบนหน้าเว็บ
   */
  bodyType: 'suv' | 'sedan' | 'hatch' | 'mpv';
  /**
   * เช่น SUV ไฟฟ้า หรือ ซีดานไฮบริด DM-i
   */
  tagline: string;
  /**
   * กรอกตัวเลขล้วน ไม่ต้องใส่ลูกน้ำ เช่น 1249900
   */
  priceFrom: number;
  rangeKm?: number | null;
  colorsCount?: number | null;
  /**
   * รูปที่ขึ้นบนการ์ดในหน้าแรก ควรเป็นรูปแนวนอน พื้นหลังโล่ง
   */
  heroImage?: (number | null) | Media;
  /**
   * รูปในหน้ารายละเอียดรุ่น เพิ่มได้ไม่จำกัด
   */
  gallery?: (number | Media)[] | null;
  /**
   * เพิ่มได้เท่าที่ต้องการ เช่น "มอเตอร์" / "230 แรงม้า"
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ติ๊กแล้วรุ่นนี้จะแสดงในหน้า "บริการรถให้เช่า"
   */
  rentalAvailable?: boolean | null;
  rentalDaily?: number | null;
  rentalMonthly?: number | null;
  /**
   * มีผลกับ Google โดยตรง — คำถามที่ใส่ที่นี่มีโอกาสขึ้นเป็นกล่องคำตอบในหน้าผลค้นหา เขียนคำถามให้เหมือนที่ลูกค้าพิมพ์จริง
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * เลขน้อยขึ้นก่อน
   */
  sortOrder?: number | null;
  /**
   * เอาเครื่องหมายออก = ซ่อนรุ่นนี้จากเว็บโดยไม่ต้องลบ
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * อัปโหลดรูปครั้งเดียว นำไปใช้ซ้ำได้ทุกหน้า
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * อธิบายสั้นๆ ว่ารูปนี้คืออะไร เช่น "BYD Sealion 7 สีขาว มุมหน้า" — Google ใช้ข้อความนี้
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * โปรฯ ที่เลยวันสิ้นสุดจะหายจากเว็บเองอัตโนมัติ ไม่ต้องมาลบ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  /**
   * 1–2 บรรทัดพอ ข้อความยาวจะถูกตัดบนการ์ด
   */
  summary: string;
  /**
   * คำสั้นๆ บนมุมการ์ด เช่น ไฮไลต์ / ทดลองขับ / เทิร์นรถเก่า
   */
  badge?: string | null;
  /**
   * การ์ดจะใหญ่และมีพื้นหลังแดง — ควรเลือกแค่อันเดียว
   */
  featured?: boolean | null;
  /**
   * เว้นว่าง = แสดงทันที
   */
  startDate?: string | null;
  /**
   * เว้นว่าง = แสดงตลอด
   */
  endDate?: string | null;
  image?: (number | null) | Media;
  ctaLabel?: string | null;
  /**
   * เช่น /test-drive
   */
  ctaHref?: string | null;
  /**
   * เว้นว่าง = แสดงทุกสาขา เลือกสาขา = แสดงเฉพาะเว็บสาขานั้น
   */
  branches?: (number | Branch)[] | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ข้อมูลสาขาที่แสดงบนเว็บ — รหัสสาขาต้องตรงกับในระบบ CRM
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  nameEn?: string | null;
  /**
   * ต้องตรงกับรหัสในระบบ CRM: ratchada, ladprao, rama5, bonmarche, kanchana
   */
  code: string;
  /**
   * รูปแบบ 062-673-1999
   */
  phone: string;
  openHours?: string | null;
  address?: string | null;
  /**
   * กดปุ่ม "แชร์" ใน Google Maps แล้ววางลิงก์ที่นี่
   */
  mapUrl?: string | null;
  /**
   * เช่น bydhiclassratchada.com — เว้นว่างถ้าสาขานี้ยังไม่มีเว็บของตัวเอง
   */
  domain?: string | null;
  /**
   * สำคัญมาก — เขียนให้ต่างจากสาขาอื่นจริงๆ เล่าถึงย่านนั้น ทีมงาน สิ่งที่สาขานี้เด่น ห้ามคัดลอกจากสาขาอื่น
   */
  intro?: string | null;
  photos?: (number | Media)[] | null;
  team?:
    | {
        name: string;
        role?: string | null;
        phone?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * ตัวพิมพ์เล็กและขีดกลาง เช่น byd-big-motor-sale-2026
   */
  slug: string;
  category?: ('news' | 'event' | 'guide' | 'service') | null;
  publishedAt: string;
  /**
   * ข้อความที่ขึ้นบนการ์ดและใน Google
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName?: string | null;
  /**
   * ทีมการตลาดเลือก "ทีมการตลาด" พอครับ
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'car-models';
        value: number | CarModel;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-models_select".
 */
export interface CarModelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bodyType?: T;
  tagline?: T;
  priceFrom?: T;
  rangeKm?: T;
  colorsCount?: T;
  heroImage?: T;
  gallery?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  rentalAvailable?: T;
  rentalDaily?: T;
  rentalMonthly?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  badge?: T;
  featured?: T;
  startDate?: T;
  endDate?: T;
  image?: T;
  ctaLabel?: T;
  ctaHref?: T;
  branches?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  code?: T;
  phone?: T;
  openHours?: T;
  address?: T;
  mapUrl?: T;
  domain?: T;
  intro?: T;
  photos?: T;
  team?:
    | T
    | {
        name?: T;
        role?: T;
        phone?: T;
        photo?: T;
        id?: T;
      };
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * ข้อความและตัวเลขที่ใช้ร่วมกันทั้งเว็บ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  heroHeadline: string;
  heroHeadline2?: string | null;
  heroSub?: string | null;
  heroBlurb?: string | null;
  mainPhone: string;
  lineUrl?: string | null;
  facebookUrl?: string | null;
  footerAbout?: string | null;
  /**
   * ใส่เป็นเปอร์เซ็นต์ เช่น 2.89 — เครื่องคำนวณบนเว็บจะใช้ค่านี้ทันทีที่บันทึก
   */
  financeRate: number;
  defaultDownPercent?: number | null;
  defaultTerm?: number | null;
  financeNote?: string | null;
  /**
   * ค่านี้จะถูกเขียนลงช่อง lead_source ในระบบ CRM เพื่อให้แยกออกว่าลีดมาจากเว็บ
   */
  leadSourceLabel: string;
  /**
   * ลีดจากเว็บจะลงชื่อนี้ก่อน แล้วให้หัวหน้าสาขากดรับในพอร์ทัล
   */
  leadHolderName: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroHeadline?: T;
  heroHeadline2?: T;
  heroSub?: T;
  heroBlurb?: T;
  mainPhone?: T;
  lineUrl?: T;
  facebookUrl?: T;
  footerAbout?: T;
  financeRate?: T;
  defaultDownPercent?: T;
  defaultTerm?: T;
  financeNote?: T;
  leadSourceLabel?: T;
  leadHolderName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}