/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'car-models': CarModel;
    promotions: Promotion;
    news: News;
    branches: Branch;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'car-models': CarModelsSelect<false> | CarModelsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'page-content': PageContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'page-content': PageContentSelect<false> | PageContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * แก้ราคาและสเปกรถทุกรุ่นที่นี่ — แก้แล้วเว็บอัปเดตทันที
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-models".
 */
export interface CarModel {
  id: number;
  /**
   * เช่น Sealion 7
   */
  name: string;
  /**
   * ตัวพิมพ์เล็กและขีดกลาง เช่น sealion-7 — เปลี่ยนแล้วลิงก์เดิมจะเสีย
   */
  slug: string;
  /**
   * ใช้สำหรับปุ่มกรองบนหน้าเว็บ
   */
  bodyType: 'suv' | 'sedan' | 'hatch' | 'mpv';
  powertrain: 'ev' | 'phev';
  /**
   * เช่น SUV ไฟฟ้า หรือ ซีดานไฮบริด DM-i
   */
  tagline: string;
  /**
   * กรอกตัวเลขล้วน ไม่ต้องใส่ลูกน้ำ เช่น 1249900
   */
  priceFrom: number;
  rangeKm?: number | null;
  colorsCount?: number | null;
  /**
   * เช่น Premium 1,199,900 / AWD Performance 1,299,900 — ใส่แล้วหน้ารุ่นรถและหน้าตารางผ่อนจะแสดงทุกรุ่นย่อย ถ้าเว้นว่างจะใช้ "ราคาเริ่มต้น" ด้านบนอย่างเดียว
   */
  variants?:
    | {
        /**
         * เช่น Premium, Extended, AWD Performance
         */
        name: string;
        price: number;
        /**
         * เช่น มอเตอร์คู่ 530 แรงม้า
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * รูปที่ขึ้นบนการ์ดหน้าแรกและหัวหน้ารุ่น · ขนาดที่ต้องการ 1600 × 900 px (แนวนอน 16:9) · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน · พื้นหลังโล่งหรือ PNG พื้นหลังโปร่งใสจะสวยที่สุด
   */
  heroImage?: (number | null) | Media;
  /**
   * รูปในหน้ารายละเอียดรุ่น เพิ่มได้ไม่จำกัด · ขนาดที่ต้องการ 1600 × 1200 px (แนวนอน 4:3) · บนมือถือภาพจะถูกครอบจากกึ่งกลาง — วางรถ/ข้อความสำคัญไว้กลางภาพ อย่าชิดขอบ · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน
   */
  gallery?: (number | Media)[] | null;
  /**
   * เพิ่มได้เท่าที่ต้องการ เช่น "มอเตอร์" / "230 แรงม้า"
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ติ๊กแล้วรุ่นนี้จะแสดงในหน้า "บริการรถให้เช่า"
   */
  rentalAvailable?: boolean | null;
  rentalDaily?: number | null;
  rentalMonthly?: number | null;
  /**
   * ราคาต่อวัน รวม VAT แล้ว · ยิ่งเช่านานยิ่งถูกลง ใส่ครบทั้ง 4 ช่อง (1 / 3 / 7 / 30 วัน) แล้วหน้าเช่ารถจะขึ้นเป็นตารางให้อัตโนมัติ ถ้าเว้นว่างจะใช้ค่าเช่ารายวัน/รายเดือนด้านบนแทน
   */
  rentalRates?:
    | {
        /**
         * เช่น Standard, Extended, Dynamic
         */
        variant: string;
        day1?: number | null;
        day3?: number | null;
        day7?: number | null;
        day30?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * มีผลกับ Google โดยตรง — คำถามที่ใส่ที่นี่มีโอกาสขึ้นเป็นกล่องคำตอบในหน้าผลค้นหา เขียนคำถามให้เหมือนที่ลูกค้าพิมพ์จริง
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * เลขน้อยขึ้นก่อน
   */
  sortOrder?: number | null;
  /**
   * เอาเครื่องหมายออก = ซ่อนรุ่นนี้จากเว็บโดยไม่ต้องลบ
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * อัปโหลดรูปครั้งเดียว นำไปใช้ซ้ำได้ทุกหน้า · ขนาดต้นฉบับควรกว้างอย่างน้อย 1600 px (รูปแบนเนอร์เต็มจอใช้ 1920 px) ระบบจะย่อเป็น 3 ขนาดให้เอง: 400 px สำหรับรูปเล็ก · 800 px สำหรับการ์ด · 1920 px สำหรับภาพเต็มจอ · ห้ามอัปโหลดรูปที่กว้างน้อยกว่า 800 px เพราะจะแตกบนจอคอม
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * อธิบายสั้นๆ ว่ารูปนี้คืออะไร เช่น "BYD Sealion 7 สีขาว มุมหน้า" — Google ใช้ข้อความนี้
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * โปรฯ ที่เลยวันสิ้นสุดจะหายจากเว็บเองอัตโนมัติ ไม่ต้องมาลบ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  /**
   * 1–2 บรรทัดพอ ข้อความยาวจะถูกตัดบนการ์ด
   */
  summary: string;
  /**
   * คำสั้นๆ บนมุมการ์ด เช่น ไฮไลต์ / ทดลองขับ / เทิร์นรถเก่า
   */
  badge?: string | null;
  /**
   * การ์ดจะใหญ่และมีพื้นหลังแดง — ควรเลือกแค่อันเดียว
   */
  featured?: boolean | null;
  /**
   * เว้นว่าง = แสดงทันที
   */
  startDate?: string | null;
  /**
   * เว้นว่าง = แสดงตลอด
   */
  endDate?: string | null;
  /**
   * ขนาดที่ต้องการ 1600 × 900 px (แนวนอน 16:9) · บนมือถือภาพจะถูกครอบจากกึ่งกลาง — วางรถ/ข้อความสำคัญไว้กลางภาพ อย่าชิดขอบ · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน
   */
  image?: (number | null) | Media;
  ctaLabel?: string | null;
  /**
   * เช่น /test-drive
   */
  ctaHref?: string | null;
  /**
   * เว้นว่าง = แสดงทุกสาขา เลือกสาขา = แสดงเฉพาะเว็บสาขานั้น
   */
  branches?: (number | Branch)[] | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ข้อมูลสาขาที่แสดงบนเว็บ — รหัสสาขาต้องตรงกับในระบบ CRM
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  nameEn?: string | null;
  /**
   * ต้องตรงกับรหัสในระบบ CRM: ratchada, ladprao, rama5, bonmarche, kanchana
   */
  code: string;
  /**
   * รูปแบบ 062-673-1999
   */
  phone: string;
  openHours?: string | null;
  address?: string | null;
  /**
   * เช่น https://line.me/R/ti/p/@bydhiclassladprao — ปุ่ม LINE บนหน้าสาขานี้จะไปหาสาขาโดยตรง ถ้าเว้นว่างจะใช้ LINE กลางจากตั้งค่าเว็บไซต์
   */
  lineUrl?: string | null;
  /**
   * กดปุ่ม "แชร์" ใน Google Maps แล้ววางลิงก์ที่นี่
   */
  mapUrl?: string | null;
  /**
   * เช่น https://www.facebook.com/BYDHiclassLadprao
   */
  facebookUrl?: string | null;
  /**
   * เช่น https://www.instagram.com/bydhiclassladprao
   */
  instagramUrl?: string | null;
  /**
   * เช่น https://www.tiktok.com/@bydhiclassladprao
   */
  tiktokUrl?: string | null;
  /**
   * เช่น https://www.youtube.com/@bydhiclassladprao
   */
  youtubeUrl?: string | null;
  /**
   * เช่น bydhiclassratchada.com — เว้นว่างถ้าสาขานี้ยังไม่มีเว็บของตัวเอง
   */
  domain?: string | null;
  /**
   * สำคัญมาก — เขียนให้ต่างจากสาขาอื่นจริงๆ เล่าถึงย่านนั้น ทีมงาน สิ่งที่สาขานี้เด่น ห้ามคัดลอกจากสาขาอื่น
   */
  intro?: string | null;
  /**
   * ขนาดที่ต้องการ 1600 × 1200 px (แนวนอน 4:3) · บนมือถือภาพจะถูกครอบจากกึ่งกลาง — วางรถ/ข้อความสำคัญไว้กลางภาพ อย่าชิดขอบ · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน
   */
  photos?: (number | Media)[] | null;
  team?:
    | {
        name: string;
        role?: string | null;
        phone?: string | null;
        /**
         * ขนาดที่ต้องการ 800 × 800 px (จัตุรัส 1:1) · ถ่ายครึ่งตัว หน้าอยู่กลางภาพ · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * ตัวพิมพ์เล็กและขีดกลาง เช่น byd-big-motor-sale-2026
   */
  slug: string;
  category?: ('news' | 'event' | 'guide' | 'service') | null;
  publishedAt: string;
  /**
   * ข้อความที่ขึ้นบนการ์ดและใน Google
   */
  excerpt: string;
  /**
   * ขนาดที่ต้องการ 1600 × 900 px (แนวนอน 16:9) · บนมือถือภาพจะถูกครอบจากกึ่งกลาง — วางรถ/ข้อความสำคัญไว้กลางภาพ อย่าชิดขอบ · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน
   */
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName?: string | null;
  /**
   * ทีมการตลาดเลือก "ทีมการตลาด" พอครับ
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'car-models';
        value: number | CarModel;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-models_select".
 */
export interface CarModelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bodyType?: T;
  powertrain?: T;
  tagline?: T;
  priceFrom?: T;
  rangeKm?: T;
  colorsCount?: T;
  variants?:
    | T
    | {
        name?: T;
        price?: T;
        note?: T;
        id?: T;
      };
  heroImage?: T;
  gallery?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  rentalAvailable?: T;
  rentalDaily?: T;
  rentalMonthly?: T;
  rentalRates?:
    | T
    | {
        variant?: T;
        day1?: T;
        day3?: T;
        day7?: T;
        day30?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  badge?: T;
  featured?: T;
  startDate?: T;
  endDate?: T;
  image?: T;
  ctaLabel?: T;
  ctaHref?: T;
  branches?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  code?: T;
  phone?: T;
  openHours?: T;
  address?: T;
  lineUrl?: T;
  mapUrl?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  youtubeUrl?: T;
  domain?: T;
  intro?: T;
  photos?: T;
  team?:
    | T
    | {
        name?: T;
        role?: T;
        phone?: T;
        photo?: T;
        id?: T;
      };
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * ข้อความและตัวเลขที่ใช้ร่วมกันทั้งเว็บ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  heroHeadline: string;
  heroHeadline2?: string | null;
  heroSub?: string | null;
  heroBlurb?: string | null;
  /**
   * เช่น 3500 — เว็บจะแสดงเป็น "3,500+ คัน"
   */
  deliveredCount?: number | null;
  yearsOpen?: number | null;
  googleRating?: number | null;
  /**
   * เช่น ศูนย์บริการมาตรฐาน BYD ครบทั้ง 5 สาขา ช่างผ่านการอบรมจากโรงงาน
   */
  trustNote?: string | null;
  /**
   * ขึ้นต้นด้วย G- เช่น G-ABC123XYZ (Analytics → Admin → Data Streams) — จะโหลดเฉพาะเมื่อผู้ใช้กดยอมรับคุกกี้ตาม PDPA
   */
  gaMeasurementId?: string | null;
  /**
   * เฉพาะค่าใน content="..." ของ meta tag ที่ Search Console ให้มา
   */
  googleSiteVerification?: string | null;
  googleAdsId?: string | null;
  adsLabelTestDrive?: string | null;
  adsLabelRegister?: string | null;
  adsLabelPhone?: string | null;
  adsLabelLine?: string | null;
  mainPhone: string;
  /**
   * สำคัญ — ปุ่ม "แอด LINE" ทุกหน้าใช้ลิงก์นี้ เช่น https://lin.ee/xxxxx (ถ้าเว้นว่างปุ่มจะกลายเป็น "ติดต่อเรา")
   */
  lineUrl?: string | null;
  facebookUrl?: string | null;
  contactEmail?: string | null;
  footerAbout?: string | null;
  /**
   * ใส่เป็นเปอร์เซ็นต์ เช่น 2.89 — เครื่องคำนวณบนเว็บจะใช้ค่านี้ทันทีที่บันทึก
   */
  financeRate: number;
  defaultDownPercent?: number | null;
  defaultTerm?: number | null;
  financeNote?: string | null;
  /**
   * ค่านี้จะถูกเขียนลงช่อง lead_source ในระบบ CRM เพื่อให้แยกออกว่าลีดมาจากเว็บ
   */
  leadSourceLabel: string;
  /**
   * ลีดจากเว็บจะลงชื่อนี้ก่อน แล้วให้หัวหน้าสาขากดรับในพอร์ทัล
   */
  leadHolderName: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * แก้ข้อความบนหน้า รางวัล · รถเช่า · ศูนย์บริการ · เทิร์นรถเก่า ได้ที่นี่ทั้งหมด — ช่องไหนเว้นว่างจะใช้ข้อความเดิมที่ตั้งไว้ให้
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: number;
  /**
   * เช่น BYD Dealer of the Year 2025
   */
  awKicker?: string | null;
  /**
   * ต้องมีเสมอเมื่อเคลม "อันดับ 1" เช่น ข้อมูล Hi-Class Group รวมทุกสาขา ณ กันยายน 2569
   */
  awAsOf?: string | null;
  awHeadline?: string | null;
  awHeadline2?: string | null;
  awLead?: string | null;
  /**
   * แนวตั้ง 3:4 · ขนาดที่ต้องการ 1200 × 1600 px (แนวตั้ง 3:4) · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน
   */
  awHeroImage?: (number | null) | Media;
  /**
   * เช่น No.1 / ยอดขายกลุ่มดีลเลอร์ BYD ทั่วประเทศ
   */
  awStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * เรียงตามปีให้อัตโนมัติ ปีล่าสุดขึ้นก่อน · ใส่ "จำนวนรางวัล" เฉพาะรางวัลทีมช่าง (จะไปอยู่ในบล็อกทีมช่างแทน)
   */
  awItems?:
    | {
        year: number;
        /**
         * Google ใช้ข้อความนี้
         */
        title: string;
        level: 'national' | 'apac';
        th: string;
        event: string;
        /**
         * เว้นว่างถ้าได้ใบเดียว
         */
        count?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * รูปจะไปขึ้นข้างรายการรางวัลของปีนั้น
   */
  awYearPhotos?:
    | {
        year: number;
        /**
         * ขนาดที่ต้องการ 1600 × 1200 px (แนวนอน 4:3) · บนมือถือภาพจะถูกครอบจากกึ่งกลาง — วางรถ/ข้อความสำคัญไว้กลางภาพ อย่าชิดขอบ · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  awTechTitle?: string | null;
  awTechSub?: string | null;
  awTechNote?: string | null;
  /**
   * ขนาดที่ต้องการ 1600 × 900 px (แนวนอน 16:9) · ไฟล์ไม่เกิน 5 MB · JPG / PNG / WebP · ระบบย่อและแปลงเป็น WebP ให้เองไม่ต้องย่อมาก่อน
   */
  awTechImage?: (number | null) | Media;
  awCtaTitle?: string | null;
  awCtaSub?: string | null;
  /**
   * ยาวไม่เกิน ~60 ตัวอักษร ใส่คำที่ลูกค้าเสิร์ชจริงไว้ต้นประโยค
   */
  awSeoTitle?: string | null;
  /**
   * ยาวไม่เกิน ~155 ตัวอักษร
   */
  awSeoDesc?: string | null;
  rtKicker?: string | null;
  rtTitle?: string | null;
  /**
   * พิมพ์ {สาขา} ตรงไหน ระบบจะแทนด้วยจำนวนสาขาที่เปิดอยู่จริงให้เอง เช่น "รับรถได้ที่ {สาขา} สาขา"
   */
  rtLead?: string | null;
  /**
   * เช่น เงื่อนไขราคา ภาษี จำนวนรถจำกัด
   */
  rtFineprint?: string | null;
  /**
   * มีผลกับ Google โดยตรง — คำถามที่ใส่ที่นี่มีโอกาสขึ้นเป็นกล่องคำตอบในหน้าผลค้นหา เขียนคำถามให้เหมือนที่ลูกค้าพิมพ์จริง · ลบให้เหลือ 0 ข้อ = ซ่อนทั้งบล็อกจากหน้าเว็บ
   */
  rtFaq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ยาวไม่เกิน ~60 ตัวอักษร ใส่คำที่ลูกค้าเสิร์ชจริงไว้ต้นประโยค
   */
  rtSeoTitle?: string | null;
  /**
   * ยาวไม่เกิน ~155 ตัวอักษร
   */
  rtSeoDesc?: string | null;
  svKicker?: string | null;
  /**
   * พิมพ์ {สาขา} แทนจำนวนสาขาได้ เช่น "ศูนย์บริการ BYD ทั้ง {สาขา} สาขา"
   */
  svTitle?: string | null;
  /**
   * ใช้ {สาขา} ได้เหมือนกัน
   */
  svLead?: string | null;
  /**
   * การ์ดบริการที่ขึ้นบนสุดของหน้า — ลบให้เหลือ 0 = ซ่อนทั้งบล็อก
   */
  svServices?:
    | {
        icon?:
          | ('wrench' | 'shield' | 'bolt' | 'key' | 'car' | 'wheel' | 'clock' | 'phone' | 'chat' | 'pin' | 'check')
          | null;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * มีผลกับ Google โดยตรง — คำถามที่ใส่ที่นี่มีโอกาสขึ้นเป็นกล่องคำตอบในหน้าผลค้นหา เขียนคำถามให้เหมือนที่ลูกค้าพิมพ์จริง · ลบให้เหลือ 0 ข้อ = ซ่อนทั้งบล็อกจากหน้าเว็บ
   */
  svFaq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ยาวไม่เกิน ~60 ตัวอักษร ใส่คำที่ลูกค้าเสิร์ชจริงไว้ต้นประโยค
   */
  svSeoTitle?: string | null;
  /**
   * ยาวไม่เกิน ~155 ตัวอักษร
   */
  svSeoDesc?: string | null;
  tiKicker?: string | null;
  tiTitle?: string | null;
  tiLead?: string | null;
  /**
   * มีผลกับ Google โดยตรง — คำถามที่ใส่ที่นี่มีโอกาสขึ้นเป็นกล่องคำตอบในหน้าผลค้นหา เขียนคำถามให้เหมือนที่ลูกค้าพิมพ์จริง · ลบให้เหลือ 0 ข้อ = ซ่อนทั้งบล็อกจากหน้าเว็บ
   */
  tiFaq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ยาวไม่เกิน ~60 ตัวอักษร ใส่คำที่ลูกค้าเสิร์ชจริงไว้ต้นประโยค
   */
  tiSeoTitle?: string | null;
  /**
   * ยาวไม่เกิน ~155 ตัวอักษร
   */
  tiSeoDesc?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroHeadline?: T;
  heroHeadline2?: T;
  heroSub?: T;
  heroBlurb?: T;
  deliveredCount?: T;
  yearsOpen?: T;
  googleRating?: T;
  trustNote?: T;
  gaMeasurementId?: T;
  googleSiteVerification?: T;
  googleAdsId?: T;
  adsLabelTestDrive?: T;
  adsLabelRegister?: T;
  adsLabelPhone?: T;
  adsLabelLine?: T;
  mainPhone?: T;
  lineUrl?: T;
  facebookUrl?: T;
  contactEmail?: T;
  footerAbout?: T;
  financeRate?: T;
  defaultDownPercent?: T;
  defaultTerm?: T;
  financeNote?: T;
  leadSourceLabel?: T;
  leadHolderName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content_select".
 */
export interface PageContentSelect<T extends boolean = true> {
  awKicker?: T;
  awAsOf?: T;
  awHeadline?: T;
  awHeadline2?: T;
  awLead?: T;
  awHeroImage?: T;
  awStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  awItems?:
    | T
    | {
        year?: T;
        title?: T;
        level?: T;
        th?: T;
        event?: T;
        count?: T;
        id?: T;
      };
  awYearPhotos?:
    | T
    | {
        year?: T;
        image?: T;
        id?: T;
      };
  awTechTitle?: T;
  awTechSub?: T;
  awTechNote?: T;
  awTechImage?: T;
  awCtaTitle?: T;
  awCtaSub?: T;
  awSeoTitle?: T;
  awSeoDesc?: T;
  rtKicker?: T;
  rtTitle?: T;
  rtLead?: T;
  rtFineprint?: T;
  rtFaq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  rtSeoTitle?: T;
  rtSeoDesc?: T;
  svKicker?: T;
  svTitle?: T;
  svLead?: T;
  svServices?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  svFaq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  svSeoTitle?: T;
  svSeoDesc?: T;
  tiKicker?: T;
  tiTitle?: T;
  tiLead?: T;
  tiFaq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  tiSeoTitle?: T;
  tiSeoDesc?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}